;BallPlayer Behaviour settings
unknown_10 = 15
unknown_09 = 100
unknown_13 = 180
unknown_06 = 0
unknown_01 = 0
unknown_03 = 1
unknown_15 = 32
unknown_00 = 1
unknown_12 = 360
unknown_05 = 1
unknown_08 = 1
unknown_02 = 0
unknown_14 = 0
unknown_07 = 0
unknown_11 = 28
unknown_04 = 0
