;BallPlayer Behaviour settings
unknown_00 = 60
unknown_01 = 40
unknown_02 = 30
unknown_03 = 20
unknown_04 = 10
unknown_05 = 0
unknown_06 = 0
unknown_07 = 0
unknown_08 = 40
unknown_09 = 30
unknown_10 = 20
unknown_11 = 10
unknown_12 = 5
unknown_13 = 0
unknown_14 = 0
unknown_15 = 0
